import coursesSlice from '../slices/coursesSlice'

export const {
  fetchCoursesRequest,
  fetchCoursesSuccess,
  fetchCoursesFailure,
  fetchCourseRequest,
  fetchCourseSuccess,
  fetchCourseFailure,
  fetchTeacherCoursesRequest,
  fetchTeacherCoursesSuccess,
  fetchTeacherCoursesFailure,
  fetchUserCoursesRequest,
  fetchUserCoursesSuccess,
  fetchUserCoursesFailure,
  publishCourseRequest,
  publishCourseSuccess,
  publishCourseFailure,
  createCourseRequest,
  createCourseSuccess,
  createCourseFailure,
  updateCourseRequest,
  updateCourseSuccess,
  updateCourseFailure,
  editCourseHeaderImageRequest,
  editCourseHeaderImageSuccess,
  editCourseHeaderImageFailure,
  addUsersCourseRequest,
  addUsersCourseSuccess,
  addUsersCourseFailure,
  deleteCourseRequest,
  deleteCourseSuccess,
  deleteCourseFailure,
  visibilityRequest,
  visibilitySuccess,
  visibilityFailure,
  joinTheCourseRequest,
  joinTheCourseSuccess,
  joinTheCourseFailure,
  clearCourse,
  clearCourses,
} = coursesSlice.actions
