export default [
  {
    id: 1,
    title: 'Web-дизайнер',
    price: '5500',
    date: '24 месяца',
    category: 'Бесплатный курс',
  },
  {
    id: 2,
    title: 'UX-UI дизайнер',
    price: '5500',
    date: '24 месяца',
    category: 'Бесплатный курс',
  },
  {
    id: 3,
    title: 'Frontend-разработчик',
    price: '5500',
    date: '24 месяца',
    category: 'Платный курс',
  },
  {
    id: 4,
    title: 'Backend-разработчик',
    price: '5500',
    date: '24 месяца',
    category: 'Платный курс',
  },
  {
    id: 5,
    title: 'Web-дизайнер',
    price: '5500',
    date: '24 месяца',
    category: 'Бесплатный курс',
  },
  {
    id: 6,
    title: 'UX-UI дизайнер',
    price: '5500',
    date: '24 месяца',
    category: 'Бесплатный курс',
  },
  {
    id: 7,
    title: 'Frontend-разработчик',
    price: '5500',
    date: '24 месяца',
    category: 'Платный курс',
  },
  {
    id: 8,
    title: 'Backend-разработчик',
    price: '5500',
    date: '24 месяца',
    category: 'Платный курс',
  },
  {
    id: 9,
    title: 'Web-дизайнер',
    price: '5500',
    date: '24 месяца',
    category: 'Бесплатный курс',
  },
]
